# Generated by Django 4.2.1 on 2023-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_likeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
