# Generated by Django 4.2.1 on 2023-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=500)),
            ],
        ),
    ]
