# Generated by Django 4.2.2 on 2023-06-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomNotification',
        ),
    ]
