# Generated by Django 3.2.19 on 2023-06-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
