# Generated by Django 3.2.19 on 2023-06-07 08:35

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20230606_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.get_upload_path),
        ),
    ]
