# Generated by Django 4.2.2 on 2023-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
