# Generated by Django 3.2.19 on 2023-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20230613_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('upvote', 'Upvote'), ('downvote', 'Downvote')], default='temporary', max_length=20),
        ),
    ]
