# Generated by Django 3.2.19 on 2023-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('follow', 'Follow'), ('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=20, null=True),
        ),
    ]
